### ISSUE TITLE
Documentation: Option 'excludes' is really 'exclude'

### ISSUE THREAD

**Issue by mtraynham** [SitePen/dts-generator#107]
> `excludes?: string[]`: A list of glob patterns, relative to `baseDir`, that should be excluded from the bundle. Use the `--exclude` flag one or more times on the command-line. Defaults to `[ "node_modules/**/*.d.ts" ]`.

This is really `exclude?: string[]` with no 's'.

**Comment by dylans** [comment]
This was fixed in #108
