### ISSUE TITLE
Excluded files should be relative to 'baseDir' value

### ISSUE THREAD

**Issue by hirikarate** [SitePen/dts-generator#112]
I have a project whose structure is like this:
```
src/
 |_ app/
    |_ *.ts files
 |_ test/
    |_ *.spec.ts files
typings/
tsconfig.json
tslint.json
```

tsconfig.json
```
"compilerOptions": {
  "rootDir": "src",
  "outDir": "dist"
}
```

The using code
```
const dts = require('dts-generator').default;
// Other "require" calls

const config = {
  name: 'my-project-name',
  project: process.cwd(),
  out: path.join(process.cwd(), 'typings', 'app.d.ts'),
  sendMessage: console.log,
  exclude: ['test/**/*.*']
};

await dts(config);
```

In this case, the internal `baseDir` variable has the value of `rootDir` config which is resolved to an absolute path to "src" folder (according to [index.ts#L239](https://github.com/SitePen/dts-generator/blob/2.1.0/index.ts#L239)). Therefore all file globs specified in `exclude` config should be resolved to paths relative to `baseDir`.

However, according to [index.ts#L256](https://github.com/SitePen/dts-generator/blob/2.1.0/index.ts#L256) the `glob.sync(filename)` currently resolves filenames relative to `process.cwd`, which negates the `exclude` effect.

I recommend changing that line of code to `glob.sync(filename, { cwd: baseDir })` according to [glob's documentation](https://github.com/isaacs/node-glob#options).

**Update:** I created pull request #113 to address this issue.

**Comment by dylans** [comment]
Thanks for the PR, landed in master.
