### ISSUE TITLE
Out of date dependency's definitions cause Travis build failures

### ISSUE THREAD

**Issue by hirikarate** [SitePen/dts-generator#114]
I wanted to contribute to this project but had hard time to compile.

![dts-generator-error](https://user-images.githubusercontent.com/5905553/41190815-898cd55e-6c0f-11e8-9e66-1f72d17c54a2.png)

It turns out I am not the only one who bumps into this problem, Travis also fails when processing my pull request.

![image](https://user-images.githubusercontent.com/5905553/41190848-0581a16c-6c10-11e8-8ac6-3370fd9fa7b1.png)

The cause may be out of date TypeScript definition of dependencies like `bluebird`, `intern` (which now already come along with their own definition file), because in "package.json", `typescript` was installed with caret "^2.1.4" which now is resolved as the latest major version "2.9.1" (you should have used tidle "~"), throwing a lot of errors to old definition files.

**Comment by dylans** [comment]
dts-generator definitely seems some love to update its dependencies. If you'd like to make the updates I'm happy to review them, though I realize that may be more effort than you're interested in contributing at this time.

**Comment by msssk** [comment]
This is probably fixed in #118

**Comment by dylans** [comment]
Closed via #118 .
