### ISSUE TITLE
Don't emit private members

### ISSUE THREAD

**Issue by mtraynham** [SitePen/dts-generator#12]
Given something like this:

```
class Foo {
    private static BAR: string = 'Bar';
    private _fizzBuzz: string = 'fizzBuzz';
}
```

They seem to be emitted and untyped:
```
declare module 'test/Foo' {
    class Foo {
        static BAR:
        private _fizzBuzz;
    }
    export = Foo;
}
```

**Comment by csnover** [comment]
dts-generator doesn’t control this output, it comes from TypeScript. The same behaviour can be noted if you run `tsc -d` directly.

**Comment by csnover** [comment]
dts-generator doesn’t control this output, it comes from TypeScript. The same behaviour can be noted if you run `tsc -d` directly. Maybe you want to open a ticket upstream?

**Comment by mtraynham** [comment]
I see, I was under the impression you were restricting some visibility of emitted nodes.  Thanks for the feedback!
