### ISSUE TITLE
TypeScript Version Support

### ISSUE THREAD

**Issue by cmichaelgraham** [SitePen/dts-generator#15]
What version(s) of TypeScript are supported by `dts-generator`?

this is what i am interested in accomplishing:
![aurelia ts process](https://cloud.githubusercontent.com/assets/10272832/7151382/5f0d0d18-e2e6-11e4-825a-1e347106f1de.jpg)

[background on process so far](https://github.com/cmichaelgraham/aurelia-typescript/blob/master/generating-aurelia-type-definitions.md)

**Comment by cmichaelgraham** [comment]
looks like [TypeScript 1.5 Alpha](https://github.com/SitePen/dts-generator/commit/a238e14d41f3cb40f2f54ed3207c2abf9ea76d4d)

**Comment by dylans** [comment]
@cmichaelgraham yes, 1.5 alpha and newer

**Comment by cmichaelgraham** [comment]
thanks @dylans :)  would you be able to help me construct a proper command line to package up [the files in this folder](https://github.com/cmichaelgraham/aurelia-ts-port/tree/master/aurelia-ts/metadata)?  i'm struggling to get it right.  the public interface i'm interested in including is in index.ts

**Comment by cmichaelgraham** [comment]
i also tried

```
dts-generator --name logging --baseDir /c/a/aurelia-ts-port/aurelia-ts/logging --out logging.d.ts index.ts
```

but it generates an empty file

**Comment by dylans** [comment]
@cmichaelgraham I cloned your repo, and ran the exact command you have above, and ended up with the output at https://gist.github.com/dylans/b2718d15502d749ddb34 ... does that look right to you or am I missing something?

**Comment by cmichaelgraham** [comment]
hi @dylans :+1:  that looks much better than what i'm getting.  i'm on a pc - are you on a mac?  i've been stepping through the code and it looks like it is ignoring the files because the basedir has backslashes and the path has forward slashes

**Comment by dylans** [comment]
@cmichaelgraham indeed, I'm on a mac, and that was my first thought (that it was a pathing issue). Maybe we need to fix our path normalization code? I'll ask our team, but may not get back to you until tomorrow.

**Comment by cmichaelgraham** [comment]
here's what i'm seeing in the debugger:

![dts-generator issue 1](https://cloud.githubusercontent.com/assets/10272832/7171341/3b2a2cd8-e394-11e4-9913-d2aff1d9141d.jpg)

![dts-generator issue 2](https://cloud.githubusercontent.com/assets/10272832/7171345/4446db86-e394-11e4-8451-630432d76f6b.jpg)

![dts-generator issue 3](https://cloud.githubusercontent.com/assets/10272832/7171349/4abab726-e394-11e4-9876-fdd515f58ad4.jpg)

**Comment by cmichaelgraham** [comment]
no worries - happy to be the crash test dummy !! :+1: 

![crash test dummy](https://cloud.githubusercontent.com/assets/10272832/7171372/8a17f104-e394-11e4-8da1-c2a60ece9558.jpg)

**Comment by cmichaelgraham** [comment]
with #16, this

```javascript
var dtsGenerator = require('dts-generator')

dtsGenerator.generate({
    name: 'aurelia-logging',
    baseDir: '/a/aurelia-ts-port/aurelia-ts/logging',
    files: [ 'index.d.ts' ],
    out: 'logging.d.ts',
    main: 'aurelia-logging/index'
});
```

generates this
```javascript
declare module 'aurelia-logging/index' {
	/**
	 * This library is part of the Aurelia platform and contains a minimal but effective logging mechanism
	 * with support for log levels and pluggable log appenders.
	 *
	 * @module logging
	 */
	/**
	* Creates an instance of Error that aggregates and preserves an innerError.
	*
	* @class AggregateError
	* @constructor
	*/
	export function AggregateError(msg: any, inner: any, skipIfAlreadyAggregate?: any): any;
	/**
	* Enum specifying the levels of the logger
	*
	* @property levels
	* @type Enum
	* @for export
	*/
	export var levels: {
	    none: number;
	    error: number;
	    warn: number;
	    info: number;
	    debug: number;
	};
	/**
	* Gets an instance of a logger by the Id used when creating.
	*
	* @method getLogger
	* @param {string} id The id of the logger you wish to get an instance of.
	* @return {Logger} The instance of the logger, or creates a new logger if none exists for that Id.
	* @for export
	*/
	export function getLogger(id: any): any;
	/**
	 * Adds an appender capable of processing logs and channeling them to an output.
	 *
	 * @method addAppender
	 * @param {Object} appender An appender instance to begin processing logs with.
	 * @for export
	 */
	export function addAppender(appender: any): void;
	/**
	* Sets the level of the logging for the application loggers
	*
	* @method setLevel
	* @param {Number} level Matches an enum specifying the level of logging.
	* @for export
	*/
	export function setLevel(level: any): void;
	/**
	* The logger is essentially responsible for having log statements that appear during debugging but are squelched
	* when using the build tools, depending on the log level that is set.  The available levels are -
	* 1. none
	* 2. error
	* 3. warn
	* 4. info
	* 5. debug
	*
	* You cannot instantiate the logger directly - you must use the getLogger method instead.
	*
	* @class Logger
	* @constructor
	*/
	export class Logger {
	    id: any;
	    constructor(id: any, key: any);
	    /**
	     * Logs a debug message.
	     *
	     * @method debug
	     * @param {string} message The message to log
	     */
	    debug(): void;
	    /**
	     * Logs info.
	     *
	     * @method info
	     * @param {string} message The message to log
	     */
	    info(): void;
	    /**
	     * Logs a warning.
	     *
	     * @method warn
	     * @param {string} message The message to log
	     */
	    warn(): void;
	    /**
	     * Logs an error.
	     *
	     * @method error
	     * @param {string} message The message to log
	     */
	    error(): void;
	}

}
declare module 'aurelia-logging' {
	import main = require('aurelia-logging/index');
	export = main;
}
```

**Comment by cmichaelgraham** [comment]
dts-generator is amazing !!!  https://github.com/cmichaelgraham/aurelia-ts-port/blob/master/aurelia-dts/binding.d.ts

**Comment by dylans** [comment]
:+1: congrats, and thanks for the pull request, we'll land that soon.

**Comment by cmichaelgraham** [comment]
hi @dylans - any idea on timing?

**Comment by dylans** [comment]
Probably early next week, we're in the middle of getting a few other releases out the door

**Comment by cmichaelgraham** [comment]
ok, cool :+1: dts-generator rocks !!! :+1:
