### ISSUE TITLE
alternate to current `main` parameter's syntax

### ISSUE THREAD

**Issue by cmichaelgraham** [SitePen/dts-generator#19]
I'd like you to implement an option for an alternate to the current syntax generated for the `main` parameter.  This is what I would like it to look like:

```javascript
declare module 'aurelia-metadata' {
	export * from 'aurelia-metadata/index';
}
```

If you were to do that (and with the more complete fix [here](https://github.com/SitePen/dts-generator/commit/d4717fa65988be2cb3359ac0167d89785561f610)), i will be able to automatically generate the [Aurelia](http://aurelia.io) type definition files.

here's the code i use at the end of the `generate` function to output the above syntax:

```javascript
        if (options.main) {
            output.write(("declare module '" + options.name + "' {") + eol + indent);
            output.write(("export * from '" + options.main + "';") + eol);
            output.write('}' + eol);
            sendMessage("Aliased main module " + options.name + " to " + options.main);
        }
```

**Comment by mtraynham** [comment]
+1

**Comment by PaulAvery** [comment]
I wuold like to second this as well

**Comment by kitsonk** [comment]
I think we need to consider `namespace` wrapping as well, since `module` is no longer the preferred way of isolating these things.

**Comment by siulung4073** [comment]
+1 In my case I have an index.js as the main, and the generator outputs:

```javascript
declare module 'tss-lib/index'
```

it would be great if it could output:

```javascript
declare module 'tss-lib'
```
