### ISSUE TITLE
Generates `\` in package names on windows

### ISSUE THREAD

**Issue by basarat** [SitePen/dts-generator#20]
See example : https://github.com/cmichaelgraham/aurelia-typescript-atom/blob/9bfc978d6b79cb8960034184efdf7c773a3b7afd/aurelia-dts/aurelia-http-client.d.ts#L257-L262

Should all be `/`

Works fine on mac. /cc @cmichaelgraham

**Comment by csnover** [comment]
This was already fixed in 1.4.1 by https://github.com/SitePen/dts-generator/commit/d4717fa65988be2cb3359ac0167d89785561f610

**Comment by basarat** [comment]
Perfect thanks :rose: Will leave for @cmichaelgraham to update the sample :)

**Comment by cmichaelgraham** [comment]
sorry for the confusion, that folder is obselete (and now deleted).  

this is the [correct folder](https://github.com/cmichaelgraham/aurelia-typescript-atom/tree/master/skel-nav-ts/typings/aurelia)

you can see (as @csnover points out), the dts-generator is working properly :+1:
[aurelia-http-client.d.ts](https://github.com/cmichaelgraham/aurelia-typescript-atom/tree/master/skel-nav-ts/typings/aurelia) 

thank you @csnover for your efforts.  dts-generator is very cool !!
