### ISSUE TITLE
Warn on Non Exported Interfaces

### ISSUE THREAD

**Issue by kitsonk** [SitePen/dts-generator#21]
Currently, when dts-generator encounters an interface that is not exported, but it depended upon by something that it is exported, it silently fails to emit anything instead of warning the user that they may need to export additional interfaces as they probably intended.

For example, a developer would likely expect this to emit something via dts-generator:
```typescript
interface Foo {}

export class Bar {
    foo: Foo;
}
```

In theory, it would be useful to emit a warning of some type that the exported class is relying upon a non-exported interface.

**Comment by jason0x43** [comment]
PR #18 addresses this, although it has the build fail rather than emit a warning.

**Comment by kitsonk** [comment]
Thank for pointing that out.  Is it truly a hard fail?  Could there be a legitimate case where it is intended (which would almost indicate that a mechanism to suppress should also be addressed)?

**Comment by csnover** [comment]
Yes it is a hard failure, since the emitter currently refuses to emit anything in this case. @jason0x43 please just commit that change directly when you have a moment. Thanks!

**Comment by jason0x43** [comment]
Will do, a soon as I'm around a computer again (this weekend).
