### ISSUE TITLE
Support glob pattern

### ISSUE THREAD

**Issue by SebastianM** [SitePen/dts-generator#26]
Would be a nice feature when I'm able to use the glob pattern in the `files` option, e.g.:

``` javascript
require('dts-generator').generate({
    name: 'angular2-bootstrap',
    baseDir: './src',
    files: ['./**/*.ts'],
    out: DIR_CONFIG.dest.declaration
  });
```

**Comment by PLEEROCK** [comment]
+ yeah this is very important, just faced with it and wanted to report this. Also please add docs how to use it with gulp

**Comment by no23reason** [comment]
being able to use globs in `externs` option would be nice as well

**Comment by kitsonk** [comment]
@PLEEROCK feel free to open another issue about the usage in gulp.

**Comment by kitsonk** [comment]
Take a look at support for `tsconfig.json` in Release 1.6.0 and let me know if this is still needed.  Delegating all the file stuff to the ts compiler seems like a better, more sustainable idea.  Deferring to 1.7 for now.
