### ISSUE TITLE
Disable the generation of ECMAScript APIs

### ISSUE THREAD

**Issue by canmrt** [SitePen/dts-generator#27]
Is there a way to disable the generation of ECMAScript APIs? My generated bundle.d.ts contains following:

```js
////////////////////////////
/// ECMAScript APIs
/////////////////////////////

declare var NaN: number;


declare var Infinity: number;

/**
  * Evaluates JavaScript code and executes it. 
  * @param x A String value that contains valid JavaScript code.
  */
declare function eval(x: string): any;

/**
  * Converts A string to an integer.
  * @param s A string to convert into a number.
  * @param radix A value between 2 and 36 that specifies the base of the number in numString. 
  * If this argument is not supplied, strings with a prefix of '0x' are considered hexadecimal.
  * All other strings are considered decimal.
  */
declare function parseInt(s: string, radix?: number): number;

...

```

**Comment by markusjohnsson** [comment]
+1

running from command line:
./node_modules/dts-generator/bin/dts-generator --name test --baseDir ./ --out test.d.ts test.ts

test.ts only contains a single empty class and imports a single empty class from test2.ts.

**Comment by bmustiata** [comment]
It works fine on the latest 1.6.0-pre version.

Check out the dts-generator and do a local install (from the checked out dts-generator folder):
```
npm install -g dts-generator
```
or 
```
npm install dts-generator
```
if you like me use the grunt task.

Can you the guys release 1.6?

**Comment by bmustiata** [comment]
Actually ignore my previous comment. This happened because I was having the latest version linked into my node_modules (`npm link`), and not actually installed.

Turns out the issue happens when you want to generate your `.d.ts` file in the root of your project. Since the typescript.d.ts is inside the node_modules it actually matches that it's a transitive dependency from inside your baseDir (that is ./).

Here's a pull request:
https://github.com/SitePen/dts-generator/pull/36

**Comment by bmustiata** [comment]
As a W/A until the fix, you can add the following excludes:
```
excludes: [
    "node_modules/dts-generator/node_modules/typescript/bin/lib.core.d.ts",
    "node_modules/dts-generator/node_modules/typescript/bin/lib.core.es6.d.ts",
    "node_modules/dts-generator/node_modules/typescript/bin/lib.dom.d.ts",
    "node_modules/dts-generator/node_modules/typescript/bin/lib.d.ts",
    "node_modules/dts-generator/node_modules/typescript/bin/lib.es6.d.ts",
    "node_modules/dts-generator/node_modules/typescript/bin/lib.scriptHost.d.ts",
    "node_modules/dts-generator/node_modules/typescript/bin/lib.webworker.d.ts",
    "node_modules/dts-generator/node_modules/typescript/bin/typescript.d.ts",
    "node_modules/dts-generator/node_modules/typescript/bin/typescript_internal.d.ts",
    "node_modules/dts-generator/node_modules/typescript/bin/typescriptServices.d.ts",
    "node_modules/dts-generator/node_modules/typescript/bin/typescriptServices_internal.d.ts"
]
```

That should work since it's excluding all the .d.ts files under your baseDir that would otherwise match.

**Comment by bmustiata** [comment]
Hi @kitsonk I updated the pull request. Could you please have a look?
