### ISSUE TITLE
I can't get anything in my output having tried many options

### ISSUE THREAD

**Issue by greenGoby** [SitePen/dts-generator#28]
I am registering a task directly, and the output file is appearing, but it is not putting anything in it.  Are there options for it giving more verbose output or anything?

I am using typescript-1.5.0-beta

```js
grunt.registerTask('dts-generator', 'Generates dts files for library use of typescript from common', function () {
            require('dts-generator').generate({
                name: 'payx-common',
                baseDir: 'src/ts/data',
                // files: grunt.file.expand( 'src/ts/**/*.ts' ),
                files: [ 'BaseRemote.ts', 'BaseStatic.ts' ],
                out: 'target/temp/ts/payx-common.d.ts'
            });
        });
```

**Comment by kitsonk** [comment]
@greenGoby this is usually because you are not exporting everything you need.  See #21 and #18.  What version of `dts-generator` are you using?

**Comment by greenGoby** [comment]
I actually was able to get this fixed by using the right combinations of
the options.  If you don't have all of those matching, there is not a lot
of debug that tells you why it isn't finding any files.

**Comment by mikey0000** [comment]
@greenGoby do you mind sharing, I can't seem to get the grunt task to work.

**Comment by kitsonk** [comment]
Original issue seems to be resolved, therefore closing.
