### ISSUE TITLE
What is the purpose of the 'target' option?

### ISSUE THREAD

**Issue by markusjohnsson** [SitePen/dts-generator#31]
Hello. Thank you for your work on this tool. We are currently working on integrating it into our build.

We spent some time today debugging some weird behaviour which in the end turned out to be an error on our side: we had set "target" to "es5" thinking it should be a string, when it should have been a number, 1 for es5 or 2 for es6, which was very counter-intuitive. 

But my real concern is the existence of the "target" option - what difference does the target environment (es5 or es6) have on .d.ts files?

**Comment by kitsonk** [comment]
Internally, TypeScript services uses some of the ways of expressing the types different depending on the target.  The target is the number provided from the enumerable type that is used internally within the compiler.  I am not sure of specific cases where the output is different, but it should generally align to what you are outputting in addition to letting the compiler to know which library to use when interpreting your code.

Trying to make it so you can specify the same target that you can with `tsc` though makes sense.

**Comment by kitsonk** [comment]
Related to #34, will track there.
