### ISSUE TITLE
Update the TypeScript dependency to ^1.5.3?

### ISSUE THREAD

**Issue by sccolbert** [SitePen/dts-generator#33]
The `package.json` is requiring `1.5.0-alpha`. Could it be updated to track `^1.5.3` stable?

**Comment by jjrv** [comment]
Besides updating `package.json`, this seems to require small changes in the code. I've forked and patched `dts-generator` for new purposes as part of another project, and these commits might be sufficient to update the TypeScript version:

charto/autodts-generator@070f78a219d3d97436f8f81e94b393c7eaededb4
charto/autodts-generator@aecc5931c894943b205f5ba73e638512093acf36

**Comment by kitsonk** [comment]
Master is now up to TypeScript 1.6.2.
