### ISSUE TITLE
abstract classes are ignored

### ISSUE THREAD

**Issue by ho-ho-ho** [SitePen/dts-generator#35]
Example:
```
export abstract class ABase {
  myProp: string;

  constructor() {
    this.myProp = 'Abstract Base Class';
  }

  abstract myFunc(): void;
}
```

Abstract classes don't appear in the generated definition file at all. Is this intented ?
As a workaround, I have to generate definitions through typescript and copy-paste all abstract classes, but it would be great if dts-generator could do that.

**Comment by kitsonk** [comment]
I suspect this is a bug, because dts-generator predates the introduction of the abstract keyword in TypeScript.

**Comment by kitsonk** [comment]
Upgrading `dts-generator` to a version of TypeScript that understands the `abstract` keyword appears to resolve the issue (see commit: 7306fe79ce4bafc3d0fe62766f56c579279a3856).  Once we land PR #37 the problem will be resolved.

**Comment by ho-ho-ho** [comment]
Sounds good. Thanks !
