### ISSUE TITLE
Is 1.6-pre published?

### ISSUE THREAD

**Issue by johnman** [SitePen/dts-generator#39]
I've tried to npm install it without luck and it doesn't look like it is installed.

I've tried downloading and building it but get a large number of build errors (I couldn't install tsd since it calls out to github and that fails but it looks like you have the dts files checked in).

Does 1.6 pre work and if so is it possible to publish? I just wanted to see if it resolved an issue where it looks like the previous version + typescript 1.6 generated dts files (for the project) results in ":any" not existing in the generated dts file and compile time failures. Thanks!

**Comment by johnman** [comment]
Switching back to npm 2 and trying a fresh install seem to resolve the issue (which may be a dependency issue because everything is flattened or something totally un-related). Look forward to the 1.6 release although I'm getting by with the current one now.

**Comment by johnman** [comment]
Hi,

Sorry. Just realised that even with npm 2 if you try writing tests for your typescript component the dts file that is generated doesn't include tsx based code so the test code fails to compile if you try to include a reference to a component.

Do you have a rough idea when 1.6 pre will be published so I can test it for you?

Thanks,

John

**Comment by PLEEROCK** [comment]
+1

**Comment by johnman** [comment]
To get around the issue for now you can add a reference to the dts file generated for that specific component e.g instead of referencing combined.d.ts you reference mycomponent.d.ts which should be generated alongside mycomponent.js, you'll still need to reference jasmine.d.ts (or the testing framework you're using) but it should tie you over until 1.6 is out

**Comment by kitsonk** [comment]
Released 1.6.0 just now.
