### ISSUE TITLE
Generate single module definition

### ISSUE THREAD

**Issue by heruan** [SitePen/dts-generator#52]
How can I tell `dts-generator` to bundle all files into a single module definition?
I'd like to achieve this:
```typescript
declare module 'my-module' {
  export class Foo {
  }
  export class Bar {
  }
}
```
what I get instead is:
```typescript
declare module 'my-module/foo' {
  export class Foo {
  }
}
declare module 'my-module/bar' {
  export class Bar {
  }
}
```
This is the command I run:
```javascript
require('dts-generator').default({
  name: 'my-module',
  baseDir: '.',
  files: [ 'foo.ts', 'bar.ts' ],
  out: 'my-module.d.ts'
});
```

**Comment by kitsonk** [comment]
Currently, *dts-generator* follows the underlying structure of the TypeScript files.  If you have separate TypeScript files (modules), the output reflects that.  It does not restructure your TypeScript code.
