### ISSUE TITLE
Output file format

### ISSUE THREAD

**Issue by pdrozdowski** [SitePen/dts-generator#61]
Would it be possible to change the format of output .d.ts file? Now each class is wrapped in module having source path in names. I think it would be more elegant if it would be like follows:

```typescript
module MyModuleName {
    require(externalPackageA);
    require(externalPackageB);
    class A {}
    class B {}
    intrerface A{}
    interface B{}
}
```

**Comment by kitsonk** [comment]
This is sort of borderline on the main purpose for `dts-generator`.  Actually what I think you are suggesting is to be able to generate all the typings under a single configurable `namespace`.

Really to fundamentally change things without MicroSoft/TypeScript#7125 being resolved wouldn't make sense.  I am still hopefully one day this package will just be totally redundant.
