### ISSUE TITLE
error TS4020

### ISSUE THREAD

**Issue by taoqf** [SitePen/dts-generator#63]
import * as Extented from 'dojo/Evented';

export class Test extends Extented {
}

this would cause error: `error TS4020: Extends clause of exported class 'Test ' has or is using private name 'Extented'.`

how can i fix it?
help me, please.

**Comment by coryisbest0728** [comment]
import {Extented} from 'dojo/Evented'
U can try this way.

**Comment by coryisbest0728** [comment]
And u have to add reference path like this
/// <reference path="../../../../lib/typings/tsd.d.ts" />

**Comment by coryisbest0728** [comment]
And u have to add reference path like this
/// &ltreference path="../../../../lib/typings/tsd.d.ts" /&gt

**Comment by coryisbest0728** [comment]
And u have to add reference path like this
/// &lt;reference path="../../../../lib/typings/tsd.d.ts" /&gt;

**Comment by taoqf** [comment]
the right way is:
import Extented = require('dojo/Evented');

export class Test extends Extented {
}

**Comment by taoqf** [comment]
i don't know why it doesn't work again.

**Comment by taoqf** [comment]
both
import Evented = require('dojo/Evented');
and 
import * as Evented from 'dojo/Evented';
would not work.

**Comment by taoqf** [comment]
@coryisbest0728 [https://github.com/taoqf/test-for-dts-generator](url)

**Comment by taoqf** [comment]
[https://github.com/DefinitelyTyped/DefinitelyTyped/issues/7439](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/7439)
