### ISSUE TITLE
UNMET PEER DEPENDENCY typescript@^1.6.0

### ISSUE THREAD

**Issue by taoqf** [SitePen/dts-generator#64]
why can't i install ts-generator when i update nodejs to 5.8.0
tsc -v
Version 1.8.7
node -v
v5.8.0

**Comment by kitsonk** [comment]
npm 3 does not install [peer dependencies by itself](http://blog.npmjs.org/post/110924823920/npm-weekly-5):

>We will also be changing the behavior of peerDependencies in npm@3. We won’t be automatically downloading the peer dependency anymore. Instead, we’ll warn you if the peer dependency isn’t already installed. This requires you to resolve peerDependency conflicts yourself, manually, but in the long run this should make it less likely that you’ll end up in a tricky spot with your packages’ dependencies.

I assume that you have `tsc` installed globally, which will not be found as a `peerDependency`.  Therefore you need to perform `npm install typescript` in the same package you have `dts-generator` installed.
