### ISSUE TITLE
Change API to better align to current TypeScript norms

### ISSUE THREAD

**Issue by kitsonk** [SitePen/dts-generator#69]
The configuration of `dts-generator` does not easily align well to make it easy for someone who is currently using the TypeScript ecosystem with a `tsconfig.json` file.

We should consider breaking the API and providing a cleaner, more concise version of `dts-generator` that fits better into current TypeScript configurations.

**Comment by taoqf** [comment]
it will be nice use require instead of fs, i find require can read tsconfig.json in hanson style
