### ISSUE TITLE
Question about main option

### ISSUE THREAD

**Issue by mtraynham** [SitePen/dts-generator#7]
Hey @csnover,

I investigated this project a little more, and I like the direction you're headed.  I think you could actually use webpack for single file bundles that have multi-entry points to directly benefit from this.  

One question:

The purpose of the `main` option.  Because all the definitions are prefixed with the `name` spec, `main` could useful to require the package itself.  But... this is generating a definition that doesn't particularly exist in code.  You attach it to the definition file, but a require on that would ultimately fail in a deployment because there isn't JS backing it.

Also, it wasn't actually generating that `main` module code for some reason.  If I moved the `main` code to the top of that promise instead of after the sourceFiles output, it worked.

Thanks, and looks promising.

**Comment by csnover** [comment]
> But... this is generating a definition that doesn't particularly exist in code. You attach it to the definition file, but a require on that would ultimately fail in a deployment because there isn't JS backing it.

The “main” entry is specified either by the `main` key in package.json on Node.js, or the `main` key of an entry to the `packages` configuration option in an AMD loader.

> Also, it wasn't actually generating that main module code for some reason. If I moved the main code to the top of that promise instead of after the sourceFiles output, it worked.

Well, an error thrown while processing the source files would cause that. :) Maybe there is another bug but it worked when I tested it!

**Comment by mtraynham** [comment]
Interesting points!  I'll see if I can recreate that issue, maybe I have a definition bug somewhere.  Thanks!
