### ISSUE TITLE
Upgrade to TypeScript 2.0

### ISSUE THREAD

**Issue by kitsonk** [SitePen/dts-generator#75]
We need to upgrade `dts-generator` to support TypeScript 2.0.  It is undermined though if TS2.0 can be supported and `dts-generator` would be backwards compatible with other versions of TS or if there needs to be a branch of different versions.

There is a summary of the breaking changes with [TypeScript 2.0](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#typescript-20) that we should review and try to determine the impact on `dts-generator`.  In particular `readonly` visibility type attribute and `never` bottom type are changes that do make the emitted types incompatible with prior version of TS, though it is uncertain the impact they have on `dts-generator`.

@agubler reported that some of the `dts-generator` typings generated for the conversion of `dojo/core` caused the typings to not be consumable by `typings/typings`.  I don't know if he was able to narrow down the issue to `dts-generator`, `typings/typings` or something else.

A branch should be created and the upgrade should be attempted.  Specifically trying to use that version of `dts-generator` against branch used in dojo/core#178 and the [dojo/compose branch](https://github.com/dojo/compose/tree/feature-ts20) which have been upgraded to TS2.

**Comment by stevehansen** [comment]
Any updates? TS 2.0 has been released now...

**Comment by dylans** [comment]
https://github.com/SitePen/dts-generator/pull/79 should resolve this, we're planning to land it soon.

**Comment by Vratislav** [comment]
Can this be closed since #79 has landed?

**Comment by dylans** [comment]
@Vratislav yes, thanks for the reminder/triage!
