### ISSUE TITLE
Expose emitFiles in the public .d.ts

### ISSUE THREAD

**Issue by mhegazy** [SitePen/dts-generator#8]
If you want to make modifications to a tree and emit that, you are required to write your own emitter as emitFiles is not exposed in the public .d.ts file. tools like: https://github.com/sitepen/dts-generator would not be able to leverage the compiler API.

**Comment by mhegazy** [comment]
wow.. wrong forum. i really need to sleep. sorry about the spam.

**Comment by csnover** [comment]
:) no worries. always glad to hear from you, @mhegazy!
