### ISSUE TITLE
Folders excluded via CLI - not programatically

### ISSUE THREAD

**Issue by scniro** [SitePen/dts-generator#82]
`dts-generator --name foo --project . --exclude this/**/*.d.ts --exclude that/**/*.d.ts --out foo.d.ts`

Excludes definitions from `/this` and `/that`. However, migrating to a programatic script - I am unable to produce the same...

```
var dts = require('dts-generator');

dts.default({
    name: 'foo',
    project: './',
    exclude: ['./this/**/*.d.ts', './that/**/*.d.ts'],
    out: 'foo.d.ts'
});
```

Nothing is excluded. Tried the following glob patterns...

 - `['./this/**/*.d.ts', './that/**/*.d.ts']`

 - `['/this/**/*.d.ts', '/that/**/*.d.ts']`

 - `['this/**/*.d.ts', 'that/**/*.d.ts']`

I have tried using `excludes` as well with no success, however looking in the source code, `excludes` (plural) does nothing with no reference to the option.

What's going on here?

**Comment by scniro** [comment]
closed, I got it working sorry guys

**Comment by dylans** [comment]
No problem @scniro, if there's something we need to improve in our docs, please let us know or add a PR.
